name: Deploy GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v6

      - name: Prepare site
        run: |
          mkdir -p _site
          cp ipsj-lualatex.cls _site/
          cp bibsample.bib ebibsample.bib ipsjunsrt-e.bst  ipsjunsrt.bst _site/
          cp ipsj.cls ipsjpref.sty ipsjsort-e.bst ipsjsort.bst ipsjtech.sty _site/
          cp ses-ipsj.cls ses.sty _site/
          cp jsample.tex jsample.pdf _site/
          cp jsample-lualatex.tex jsample-lualatex.pdf _site/
          cp esample.tex esample.pdf _site/
          cp esample-lualatex.tex esample-lualatex.pdf _site/
          cp tech-jsample.tex tech-jsample.pdf _site/
          cp tech-jsample-lualatex.tex tech-jsample-lualatex.pdf _site/
          cp ses-sample.tex ses-sample.pdf _site/
          cp ses-sample-lualatex.tex ses-sample-lualatex.pdf _site/
          cp ses-esample.tex ses-esample.pdf _site/
          cp ses-esample-lualatex.tex ses-esample-lualatex.pdf _site/
          mkdir -p _src
          cp README.md _src
          echo "theme: minima" > _src/_config.yml
          echo "title: LuaLaTeXに対応する情報処理学会（IPSJ）の論文・研究報告用スタイルファイル" >> _src/_config.yml
          echo "titles_from_headings:" >> _src/_config.yml
          echo "  strip_title: true" >> _src/_config.yml

      - uses: actions/configure-pages@v6

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./_src
          verbose: true
        
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5
